# Generated by Django 2.1.7 on 2019-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_no',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
