# Generated by Django 2.1.7 on 2019-03-18 14:20

import business.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190316_1309'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Business')),
            ],
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='script',
            field=models.FileField(upload_to=business.models.script_upload_location),
        ),
        migrations.AddField(
            model_name='business_test',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Test'),
        ),
    ]
