# Generated by Django 2.1.7 on 2019-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190316_1309'),
        ('business', '0002_auto_20190318_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='business_test',
            new_name='test_business',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
