# Generated by Django 2.1.7 on 2019-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190319_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='pod_name',
            field=models.CharField(default='termi-demo', max_length=100),
            preserve_default=False,
        ),
    ]
