# Generated by Django 2.1.7 on 2019-03-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190319_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaken',
            name='testId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='business.Test'),
        ),
    ]
