# Generated by Django 2.1.7 on 2019-03-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190319_1133'),
        ('student', '0003_auto_20190319_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('queId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='business.Questions')),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='student.TestTaken')),
            ],
        ),
    ]
