# Generated by Django 2.1.7 on 2019-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190319_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
