# Generated by Django 2.1.7 on 2019-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190319_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.IntegerField(blank=None, default=0),
        ),
    ]
